name: Deploy Docs to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    release:
        name: GitHub Pages
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v1
            - name: Checkout submodules
              run: git submodule update --init --recursive

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                profile: minimal
                override: true
                components: rustfmt, rust-src

            - name: Build Documentation
              uses: actions-rs/cargo@v1
              env:
                RUSTDOCFLAGS: "--html-in-header contrib/katex-header.html"
              with:
                command: doc
                args: --all --no-deps
            - name: Convert README.md to html
              uses: maxheld83/pandoc@v2
              with:
                args: "README.md -o target/doc/index.html"

            - name: Deploy Documentation
              env:
                ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                PUBLISH_DIR: ./target/doc
                SCRIPT_MODE: true
                PUBLISH_BRANCH: gh-pages
              run: |
                wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
                bash ./entrypoint.sh
